version: '3.4'

services:
  metaexchangeservice.webapi:
    image: ${DOCKER_REGISTRY-}metaexchangeservicewebapi
    build:
      context: .
      dockerfile: UI/MetaExchangeService.WebApi/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "60666:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Qwerty@123
      - MSSQL_AGENT_ENABLED=true
